#!/usr/bin/python
import requests,sys,string
import json
import subprocess
import textwrap
import os
import dbus
import urllib
import dbus

# USE GOOGLE SPEECH API FOR BETTER ACCURACY. TO USE IT READ THE README FILE. 

using_google_speech_api = False

bus = dbus.SessionBus()
helloservice = bus.get_object('org.gnome.Shell', '/com/bear/queryInPanel')
hello = helloservice.get_dbus_method('setText', 'com.bear.queryInPanel')
changeColor = helloservice.get_dbus_method('changeColor', 'com.bear.queryInPanel')
voice_to_text = ""

def Report_to_admin(subject,content):
    return requests.post(
        "https://api.mailgun.net/v3/sandbox993e74db4dc649acb4e25e2f62e1f384.mailgun.org/messages",
        auth=("api", "key-0c4b2144b9585be0660a2ff2de1647f1"),
        data={"from": "Excited User <mailgun@sandbox993e74db4dc649acb4e25e2f62e1f384.mailgun.org>",
              "to": ["harishanand95@gmail.com"],
              "subject": subject,
              "text": content})


def send_to_extension(top_title,Content):
    popup = textwrap.fill(Content,180)
    if(len(popup) > 60):
        reply = "\n";
        reply += popup;
        hello(reply)
        call_extension()
    else:
        if popup == "":
            popup = "I dont know.. Try doing an Internet Search!"
            Report_to_admin(str(top_title),popup)
        hello(str(popup + "   "))
        

def call_extension():
    s = subprocess.check_output("xdpyinfo | grep dimensions | awk '{print $2}' | awk -Fx '{print $1, $2}'",shell=True) #screen size
    s = s.split()
    subprocess.call(["xdotool","mousemove",str(s[0]),"0"])


def record():
    cmd = "rec /tmp/test.wav rate 44k silence 1 0.1 3% 1 3.0 3% "
    subprocess.call(cmd.split())


def google_voice_call():
    cmd = "cd ~/.Bear && node index.js"
    voice_to_text_json = subprocess.check_output(cmd,shell=True)
    voice_to_text_json = str(voice_to_text_json[0:-1])
    voice_to_text_json = voice_to_text_json.replace("'","")
    voice_to_text = json.loads(voice_to_text_json)
    if not voice_to_text :
            return 0
    voice_text = voice_to_text[0]["result"][0]["alternative"][0]["transcript"]
    voice_text.encode('ascii','ignore')
    return voice_text


# Authorisation and Subscription key is obtained from api.ai. If you want to use your own api you can provide your keys by creating an account at api.ai.
def api_ai_voice_call():
    subp = subprocess.check_output(['curl','-k','-F',"request={'timezone':'America/New_York', 'lang':'en'};type=application/json", '-F',"voiceData=@/tmp/test.wav;type=audio/wav",'-H',"Authorization: Bearer d1e8a81177b64dae88326f80c2fa73d0",'-H',"ocp-apim-subscription-key: c3f08d12-f0cb-4524-b468-1c2226857018","https://api.api.ai/v1/query?v=20150910"])
    api_ai_json_response = json.loads(subp)
    return api_ai_json_response 

    
def api_ai_call(api_ai_json_response,flag):
    #places an api.ai call if command line or Google speech recognition is used 
    if flag :
         a = ['curl','-H',"Content-Type: application/json; charset=utf-8",'-H',"Authorization: Bearer d1e8a81177b64dae88326f80c2fa73d0",'-H',"ocp-apim-subscription-key: c3f08d12-f0cb-4524-b468-1c2226857018",'--data']
         b1 = "{'query':'"
         b2 = "', 'lang':'en', 'contexts':['weather', 'local']}"
         api_ai_json_response = api_ai_json_response.replace("'","")
         api_ai_json_response = api_ai_json_response.replace("\"","")
         b = b1 + str(api_ai_json_response) + b2
         c = "https://api.api.ai/v1/query?v=20150910"
         a.append(b)
         a.append(c)
         sub_response = subprocess.check_output(a)
         api_ai_json_response = json.loads(sub_response)
    reply =""
    searched_term = api_ai_json_response["result"]["resolvedQuery"]
    searched_term = searched_term.decode('utf8')
    print searched_term
    changeColor()    
    hello(searched_term)
    if api_ai_json_response["result"]["source"] == "agent":
        if api_ai_json_response["result"]["metadata"]["intentName"] == "Report Bug":
            reply += api_ai_json_response["result"]["parameters"]["reply"]
            Report_to_admin(str(searched_term),api_ai_response)
        else :
            reply += api_ai_json_response["result"]["parameters"]["reply"]
    else:
        reply += api_ai_json_response["result"]["fulfillment"]["speech"]
        changeColor()
    send_to_extension(searched_term,reply)
   
    
if  __name__ == '__main__' :
    if len(sys.argv) < 2:
        record()
        if using_google_speech_api:
            voice_text = google_voice_call()
            hello(voice_text)
            flag = True
        else:
            voice_text = api_ai_voice_call()
            flag = False
    else:
        voice_text = string.join(sys.argv[1:])
        flag = True
    api_ai_call(voice_text,flag)
